language: python

python:
  - "2.7"

env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=pep8,pyflakes

# command to install dependencies
install:
    - pip install tox

# command to run tests
script:
    - tox
